services:
  helium-card-minio:
    image: quay.io/minio/minio
    container_name: card-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "hyunbindev"
      MINIO_ROOT_PASSWORD: "@wu98061612"
    command: server /data --console-address ":9001"
    volumes:
      - 'helium_card_minio:/data'

  helium-card-db:
    image: mysql:latest
    container_name: helium-card-db
    environment:
      - MYSQL_DATABASE=helium_card
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATA_BASE=helium
    ports:
      - '3307:3306'
    volumes:
      - 'helium_card_db_data:/var/lib/mysql'

  helium-user-db:
    image: mysql:latest
    container_name: helium-user-db
    environment:
      - MYSQL_DATABASE=helium
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATA_BASE=helium
    ports:
      - '3306:3306'
    volumes:
      - 'helium_member_db_data:/var/lib/mysql'

  helium-user-redis:
    image: redis:latest
    container_name: helium-user-redis
    environment:
      - REDIS_PASSWORD=adifoanvckzxilfduaslnkqeiorqiej
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"
    volumes:
      - member_redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  Kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 1. 리스너 이름 정의 (내부용 INTERNAL, 외부용 EXTERNAL)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 2. 실제 통신할 주소 (내부 컨테이너는 29092, 로컬 PC는 9092)
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      # 3. 브로커 간 통신은 내부망(INTERNAL) 사용
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - Kafka
    ports:
      - "9080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

volumes:
  helium_member_db_data:
  helium_card_db_data:
  member_redis_data:
  helium_card_minio:
