spring:
  #dev tool
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #profile config
  config:
    activate:
      on-profile: 'dev'
  jpa:
    hibernate:
      ddl-auto: 'update'
  data:
    redis:
      host: 'localhost'
      port: 6379
      password: "${MEMBER_REDIS_PASSWORD}"
logging:
  level:
    com.hyunbindev: 'DEBUG'