server:
  port: 8080
spring:
  application:
    name: gate-way

  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: 'oauth2-authorization'
              uri: 'http://localhost:8081'
              predicates:
                - Path=/oauth2/authorization/**

            - id: 'oauth2-callback'
              uri: 'http://localhost:8081'
              predicates:
                - Path=/login/oauth2/code/**

            - id: 'test-api'
              uri: 'http://localhost:8081'
              predicates:
                - Path=/api/v1/test

            - id: 'user-service'
              uri: 'http://localhost:8081'
              predicates:
                - Path=/api/user/**
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
jwt:
  access:
    key: "${JWT_ACCESS_SECRET}"